### ISSUE TITLE
Switch to using the native API Gateway CloudFormation resources

### ISSUE THREAD

**Issue by cristim** [jthomerson/cloudformation-template-for-lambda-backed-api-gateway-with-dynamodb#1]
As of a couple of weeks ago AWS launched native CloudFormation support for the API Gateway.

It would make a lot of sense to start using it instead of the current implementation based on lambda-backed custom resources.

**Comment by sihil** [comment]
👍  Or if not then at least a message clarifying that it is using custom resources rather than the native resources since this scores well on google :)

**Comment by jthomerson** [comment]
@sihil and @cristim thanks for the feedback! This repo was originally just a test to see how difficult it was to create an entire serverless API using CloudFormation. Since the time I made this and several other repos I've adopted https://github.com/serverless/serverless instead. In their upcoming 1.0.x release (they're at RC1 now) they make your entire API - including APIGW, Lambda, IAM, etc, all into a CloudFormation stack. I'd highly recommend you evaluate the https://github.com/serverless/serverless framework yourself.

**Comment by cristim** [comment]
@jthomerson thanks for your message!

I'm also using serverless nowadays for one of my projects and I'm familiar with it.

Regarding this project, you should perhaps make it more clear in the README that this is not maintained anymore and that people should look into alternatives such as serverless or apex.
